version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix(deps)"
      include: "scope"
    ignore:
      - dependency-name: "marked"
        versions: ["*"] # Solo actualizar manualmente dependencias críticas de renderizado markdown
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "juliocesarabreup"
    assignees:
      - "juliocesarabreup"
    allow:
      - dependency-type: "all"
    security-updates: true
